## 1. What is a Dataset?

### Simple Concept

A **Dataset** is a collection of data that is used to train or test a machine learning model.

In PyTorch, a Dataset helps us **store and access input data and their corresponding labels**.

For example:

```text
House Size → House Price

1000 sq.ft → ₹50 Lakhs
1500 sq.ft → ₹75 Lakhs
2000 sq.ft → ₹100 Lakhs
```

Here:

- **Input (X)** → House Size
- **Target (y)** → House Price


### What the Example Tells

The dataset contains:

```text
X → Input features
y → Target values
```

Each input has a corresponding target:

```text
1000 → 50
1500 → 75
2000 → 100
```

A PyTorch `Dataset` provides a standard way to organize and access this data during model training.

### Key Point

**Dataset = Collection of input data and corresponding target/label data used by the model.**

In [1]:
## Python Example

import torch

X = torch.tensor([[1000], [1500], [2000]])
y = torch.tensor([[50], [75], [100]])

print(X)
print(y)


tensor([[1000],
        [1500],
        [2000]])
tensor([[ 50],
        [ 75],
        [100]])


## 2. What is a DataLoader?

### Simple Concept

A **DataLoader** takes data from a Dataset and provides it to the model in **small groups called batches**.

Instead of giving the entire dataset to the model at once:

```text
Dataset
   ↓
DataLoader
   ↓
Small batches
   ↓
Model
```

For example, if we have **1000 samples** and `batch_size=100`:

```text
Batch 1 → 100 samples
Batch 2 → 100 samples
Batch 3 → 100 samples
...
Batch 10 → 100 samples
```

---

### What the Example Tells

We have **6 samples** in the Dataset.

With:

```python
batch_size=2
```

the DataLoader divides them into **3 batches**:

```text
Batch 1 → Samples 1, 2
Batch 2 → Samples 3, 4
Batch 3 → Samples 5, 6
```

The model can process one batch at a time instead of processing all data together.

### Key Point

**DataLoader = Tool that loads Dataset data in batches for model training.**

In [2]:

### Python Example

import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.tensor([[1], [2], [3], [4], [5], [6]])
y = torch.tensor([[10], [20], [30], [40], [50], [60]])

dataset = TensorDataset(X, y)

loader = DataLoader(dataset, batch_size=2)

for X_batch, y_batch in loader:
    print("X:", X_batch)
    print("y:", y_batch)


X: tensor([[1],
        [2]])
y: tensor([[10],
        [20]])
X: tensor([[3],
        [4]])
y: tensor([[30],
        [40]])
X: tensor([[5],
        [6]])
y: tensor([[50],
        [60]])


## 3. Mini-Batches

### Simple Concept

A **mini-batch** is a small group of training samples taken from the complete dataset.

Instead of training the model using the entire dataset at once, we divide it into smaller groups.

For example:

```text
Dataset = 10 samples

Mini-batch 1 → 3 samples
Mini-batch 2 → 3 samples
Mini-batch 3 → 3 samples
Mini-batch 4 → 1 sample
```

The model processes **one mini-batch at a time**.

---

### What the Example Tells

The complete dataset has **6 samples**.

With `batch_size=2`:

```text
6 samples
   ↓
2 samples → Mini-batch 1
2 samples → Mini-batch 2
2 samples → Mini-batch 3
```

So, the model processes **2 samples at a time**.

This is called **mini-batch training**.

### Key Point

**Mini-batch = A small group of training samples processed by the model at one time.**

In [3]:
### Python Example

import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.tensor([[1], [2], [3], [4], [5], [6]])
y = torch.tensor([[10], [20], [30], [40], [50], [60]])

dataset = TensorDataset(X, y)

loader = DataLoader(dataset, batch_size=2)

for X_batch, y_batch in loader:
    print("Batch:")
    print(X_batch)
    print(y_batch)


Batch:
tensor([[1],
        [2]])
tensor([[10],
        [20]])
Batch:
tensor([[3],
        [4]])
tensor([[30],
        [40]])
Batch:
tensor([[5],
        [6]])
tensor([[50],
        [60]])


## 4. Batch Size

### Simple Concept

**Batch size** tells us **how many samples the model processes at one time**.

For example:

```python
DataLoader(dataset, batch_size=2)
```

means:

```text
2 samples → Model
2 samples → Model
2 samples → Model
...
```

---

### What the Example Tells

The dataset contains **6 samples**.

We selected:

```python
batch_size=3
```

Therefore:

```text
6 samples ÷ 3 samples per batch = 2 batches
```

```text
Batch 1 → 3 samples
Batch 2 → 3 samples
```

If we use:

```python
batch_size=2
```

we get **3 batches**.

### Key Point

**Batch size = Number of samples processed by the model at one time.**

In [4]:

### Python Example

import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.tensor([[1], [2], [3], [4], [5], [6]])
y = torch.tensor([[10], [20], [30], [40], [50], [60]])

dataset = TensorDataset(X, y)

loader = DataLoader(dataset, batch_size=3)

for X_batch, y_batch in loader:
    print("Batch size:", len(X_batch))
    print(X_batch)


Batch size: 3
tensor([[1],
        [2],
        [3]])
Batch size: 3
tensor([[4],
        [5],
        [6]])


## 5. Shuffle

### Simple Concept

**Shuffle** randomly changes the order of samples before creating batches.

We use:

```python
shuffle=True
```

This helps prevent the model from always seeing the training data in the same order.

---

### What the Example Tells

Without shuffling:

```text
1 → 2 → 3 → 4 → 5 → 6
```

With:

```python
shuffle=True
```

the order is randomly changed:

```text
5 → 2 → 1 → 6 → 4 → 3
```

The **data and labels stay matched**. Only their order changes.

### Key Point

**`shuffle=True` = Randomly changes the order of training samples before creating batches.**

In [8]:

### Python Example
import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.tensor([[1], [2], [3], [4], [5], [6]])
y = torch.tensor([[10], [20], [30], [40], [50], [60]])

dataset = TensorDataset(X, y)

loader = DataLoader(dataset, batch_size=2, shuffle=True)

for X_batch, y_batch in loader:
    print(X_batch)


tensor([[3],
        [5]])
tensor([[2],
        [1]])
tensor([[4],
        [6]])


## 6. TensorDataset

### Simple Concept

`TensorDataset` is a **built-in PyTorch Dataset** used when your data is already available as PyTorch tensors.

It combines input data (`X`) and target data (`y`) into one Dataset.

```python
dataset = TensorDataset(X, y)
```

Then each item contains:

```text
X → Input
y → Target
```

---

### What the Example Tells

`TensorDataset` keeps the input and target together.

For example:

```text
Sample 1 → X = 1, y = 10
Sample 2 → X = 2, y = 20
Sample 3 → X = 3, y = 30
Sample 4 → X = 4, y = 40
```

We can then pass this Dataset to a `DataLoader`.

```python
loader = DataLoader(dataset, batch_size=2)
```

### Key Point

**`TensorDataset` = Simple built-in PyTorch Dataset for storing tensors together as input-target pairs.**

In [9]:

### Python Example

import torch
from torch.utils.data import TensorDataset

X = torch.tensor([[1], [2], [3], [4]])
y = torch.tensor([[10], [20], [30], [40]])

dataset = TensorDataset(X, y)

print(dataset[0])
print(dataset[1])


(tensor([1]), tensor([10]))
(tensor([2]), tensor([20]))


## 7. Custom Dataset

### Simple Concept

A **Custom Dataset** is a Dataset that we create ourselves using PyTorch's `Dataset` class.

We use it when our data needs **custom processing or loading logic**.

Basic structure:

```python
class MyDataset(Dataset):
    # define how data is stored
    # define how data is accessed
```

A Custom Dataset mainly needs:

- `__len__()` → tells how many samples exist
- `__getitem__()` → gets one sample

---

### What the Example Tells

We created our own Dataset called `MyDataset`.

```text
X → Input data
y → Target data
```

`__len__()` tells PyTorch:

```text
There are 4 samples.
```

`__getitem__()` tells PyTorch:

```text
Give me the sample at this index.
```

For example:

```python
dataset[0]
```

returns the first input and target:

```text
X = 1
y = 10
```

### Key Point

**Custom Dataset = A user-defined PyTorch Dataset that controls how data is stored and accessed.**

In [10]:

### Python Example

import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([[1], [2], [3], [4]])
        self.y = torch.tensor([[10], [20], [30], [40]])

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


dataset = MyDataset()

print(dataset[0])
print(dataset[2])


(tensor([1]), tensor([10]))
(tensor([3]), tensor([30]))


## 7. Custom Dataset

### Simple Concept

A **Custom Dataset** is a Dataset that we create ourselves using PyTorch's `Dataset` class.

We use it when our data needs **custom processing or loading logic**.

Basic structure:

```python
class MyDataset(Dataset):
    # define how data is stored
    # define how data is accessed
```

A Custom Dataset mainly needs:

- `__len__()` → tells how many samples exist
- `__getitem__()` → gets one sample

---

### Python Example

```python
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([[1], [2], [3], [4]])
        self.y = torch.tensor([[10], [20], [30], [40]])

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


dataset = MyDataset()

print(dataset[0])
print(dataset[2])
```

### Output

```text
(tensor([1]), tensor([10]))
(tensor([3]), tensor([30]))
```

### What the Example Tells

We created our own Dataset called `MyDataset`.

```text
X → Input data
y → Target data
```

`__len__()` tells PyTorch:

```text
There are 4 samples.
```

`__getitem__()` tells PyTorch:

```text
Give me the sample at this index.
```

For example:

```python
dataset[0]
```

returns the first input and target:

```text
X = 1
y = 10
```

### Key Point

**Custom Dataset = A user-defined PyTorch Dataset that controls how data is stored and accessed.**

## 9. `__getitem__()`

### Simple Concept

`__getitem__()` tells PyTorch **how to retrieve one sample from the Dataset**.

It uses an **index** to get the input and its corresponding target.

```python
dataset[0]
```

means:

```text
Get the first sample.
```

---

### Python Example

```python
import torch
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([[1], [2], [3], [4]])
        self.y = torch.tensor([[10], [20], [30], [40]])

    def __getitem__(self, index):
        return self.X[index], self.y[index]


dataset = MyDataset()

print(dataset[0])
print(dataset[2])
```

### Output

```text
(tensor([1]), tensor([10]))
(tensor([3]), tensor([30]))
```

### What the Example Tells

When we write:

```python
dataset[0]
```

`__getitem__()` retrieves:

```text
X = 1
y = 10
```

When we write:

```python
dataset[2]
```

it retrieves:

```text
X = 3
y = 30
```

So, `__getitem__()` controls **how one sample is retrieved**.

### Key Point

**`__getitem__()` = Retrieves one input-target sample from the Dataset using its index.**

## 10. Create a Custom PyTorch Dataset

### Simple Concept

Now we combine:

- `Dataset`
- `__init__()`
- `__len__()`
- `__getitem__()`

to create our own PyTorch Dataset.

The structure is:

```text
Custom Dataset
      ↓
Store X and y
      ↓
__len__() → Number of samples
      ↓
__getitem__() → Get one sample
```

---

### What the Example Tells

Our Custom Dataset contains **4 samples**.

```text
House Size → House Price

1000 → 50
1500 → 75
2000 → 100
2500 → 125
```

`__len__()` tells PyTorch:

```text
There are 4 samples.
```

`__getitem__()` retrieves one sample when requested.

For example:

```python
dataset[0]
```

returns:

```text
1000 → 50
```

This Custom Dataset can now be given to a `DataLoader`.

### Key Point

**Custom Dataset = Our own PyTorch Dataset that defines how training data is stored and how individual samples are retrieved.**

In [11]:

### Python Example

import torch
from torch.utils.data import Dataset

class HouseDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([
            [1000],
            [1500],
            [2000],
            [2500]
        ], dtype=torch.float32)

        self.y = torch.tensor([
            [50],
            [75],
            [100],
            [125]
        ], dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


dataset = HouseDataset()

print("Number of samples:", len(dataset))
print("First sample:", dataset[0])
print("Third sample:", dataset[2])


Number of samples: 4
First sample: (tensor([1000.]), tensor([50.]))
Third sample: (tensor([2000.]), tensor([100.]))


## 11. Use DataLoader with Custom Dataset

### Simple Concept

After creating a Custom Dataset, we can pass it to a **DataLoader**.

The DataLoader will:

- Take samples from the Dataset
- Divide them into batches
- Optionally shuffle them

```text id="r4xw2b"
Custom Dataset
      ↓
   DataLoader
      ↓
   Mini-batches
      ↓
     Model
```

---

### What the Example Tells

Our Dataset has **4 samples**.

We set:

```python id="sy5g1j"
batch_size=2
```

So the DataLoader creates **2 samples per batch**.

```text id="7c8r2m"
Dataset → 4 samples

Batch 1 → 2 samples
Batch 2 → 2 samples
```

Because:

```python id="7vrq2m"
shuffle=True
```

the samples are randomly ordered before being placed into batches.

### Key Point

**DataLoader takes our Custom Dataset and provides the data to the model in mini-batches.**

In [15]:

### Python Example

import torch
from torch.utils.data import Dataset, DataLoader

class HouseDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([
            [1000],
            [1500],
            [2000],
            [2500]
        ], dtype=torch.float32)

        self.y = torch.tensor([
            [50],
            [75],
            [100],
            [125]
        ], dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


dataset = HouseDataset()

loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

for X_batch, y_batch in loader:
    print("X:", X_batch)
    print("y:", y_batch)


X: tensor([[2000.],
        [1000.]])
y: tensor([[100.],
        [ 50.]])
X: tensor([[1500.],
        [2500.]])
y: tensor([[ 75.],
        [125.]])


## 12. Train a Simple Model using DataLoader

### Simple Concept

Now we use the **DataLoader during model training**.

The basic training flow is:

```text
Dataset
   ↓
DataLoader
   ↓
Batch
   ↓
Model
   ↓
Prediction
   ↓
Loss
   ↓
Backward
   ↓
Update weights
```

The model processes **one batch at a time**.

---

Example:

```text
Epoch: 1 Loss: 18.42
Epoch: 2 Loss: 9.71
Epoch: 3 Loss: 5.36
...
Epoch: 10 Loss: 0.82
```

### What the Example Tells

For every epoch:

```text
DataLoader
    ↓
Get a batch
    ↓
Model makes prediction
    ↓
Calculate loss
    ↓
Calculate gradients
    ↓
Update weights
```

Because `batch_size=2`, the model processes **2 samples at a time**.

The DataLoader automatically provides the next batch.

### Key Point

**During training, DataLoader supplies mini-batches to the model, allowing the model to learn from the Dataset batch by batch.**

In [16]:

### Python Example

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader


class HouseDataset(Dataset):

    def __init__(self):
        self.X = torch.tensor([
            [1.0],
            [2.0],
            [3.0],
            [4.0]
        ])

        self.y = torch.tensor([
            [2.0],
            [4.0],
            [6.0],
            [8.0]
        ])

    def __len__(self):
        return len(self.X)

    def __getitem__(self, index):
        return self.X[index], self.y[index]


# Create Dataset
dataset = HouseDataset()

# Create DataLoader
loader = DataLoader(
    dataset,
    batch_size=2,
    shuffle=True
)

# Create model
model = nn.Linear(1, 1)

# Loss function
loss_function = nn.MSELoss()

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


# Training
for epoch in range(10):

    for X_batch, y_batch in loader:

        # Forward pass
        prediction = model(X_batch)

        # Calculate loss
        loss = loss_function(prediction, y_batch)

        # Backward pass
        optimizer.zero_grad()
        loss.backward()

        # Update weights
        optimizer.step()

    print("Epoch:", epoch + 1, "Loss:", loss.item())



Epoch: 1 Loss: 1.9923715591430664
Epoch: 2 Loss: 4.099843978881836
Epoch: 3 Loss: 3.877861261367798
Epoch: 4 Loss: 2.131969690322876
Epoch: 5 Loss: 1.3189587593078613
Epoch: 6 Loss: 0.16307218372821808
Epoch: 7 Loss: 0.4799651503562927
Epoch: 8 Loss: 0.43754032254219055
Epoch: 9 Loss: 0.39807969331741333
Epoch: 10 Loss: 0.19215157628059387


## 13. Why DataLoader is Important for Large Datasets

### Simple Concept

When a dataset is small, we can sometimes load the entire dataset into memory.

But when the dataset becomes very large, loading everything at once can require **a lot of memory**.

`DataLoader` helps by providing data **in smaller batches**.

```text id="p4r5ju"
Large Dataset
      ↓
   DataLoader
      ↓
Small Batch
      ↓
Model
      ↓
Next Batch
      ↓
Model
```

---

### Python Example

Suppose we have:

```text id="k0w4ms"
1,000,000 samples
```

Instead of processing all 1,000,000 samples at once:

```python id="kqyk9u"
batch_size=32
```

the DataLoader provides:

```text id="z4d1la"
Batch 1 → 32 samples
Batch 2 → 32 samples
Batch 3 → 32 samples
...
```

The model learns from each batch.

```python id="3z4d5a"
loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True
)
```

### What the Example Tells

A large dataset can be processed in **manageable batches** instead of sending the entire dataset to the model at once.

DataLoader also provides useful features such as:

- Mini-batch loading
- Shuffling
- Efficient data loading

This becomes especially important when working with large AI/ML datasets.

### Key Point

**DataLoader is important for large datasets because it allows the model to process data in smaller batches instead of loading and processing everything at once.**

Important things to remember:
1. Dataset → stores and provides data.
2. DataLoader → loads Dataset data in batches.
3. batch_size → number of samples processed at one time.
4. shuffle=True → randomly changes training data order.
5. TensorDataset → easy Dataset for tensors.
6. Custom Dataset → allows us to define our own data-loading logic.
7. __len__() → number of samples.
8. __getitem__() → retrieves one sample.
9. DataLoader → becomes especially useful for large datasets.