# Notebook 2 – PyTorch Fundamentals

## 1. What is PyTorch?

### Simple Concept

**PyTorch is a Python library used to build and train Deep Learning models.**

It helps us:

* Store data using tensors
* Perform mathematical operations
* Build neural networks
* Calculate gradients
* Train models
* Use CPU or GPU

### Why is it Needed?

Deep Learning involves a lot of mathematical calculations.

PyTorch provides ready-to-use tools to perform these calculations efficiently.

### Python Example

```python
import torch

print(torch.__version__)
```

### Output

```text
2.x.x
```

The exact version depends on your installation.

### Real-World Example

For a customer churn model:

```text
Customer Data
     ↓
PyTorch Tensor
     ↓
Neural Network
     ↓
Prediction
```

### Key Point

> PyTorch is a framework that gives us the tools needed to build and train Deep Learning models.

---

# 2. Why PyTorch is Used in Deep Learning

### Simple Concept

Deep Learning requires:

* Large numerical calculations
* Neural networks
* Gradient calculation
* Fast computation
* GPU support

PyTorch provides all of these.

### Why is it Needed?

Training a neural network involves repeating this process many times:

```text
Input
 ↓
Prediction
 ↓
Loss
 ↓
Gradient
 ↓
Weight Update
```

PyTorch helps us perform this process.

### Python Example

```python
import torch

x = torch.tensor([10.0, 20.0, 30.0])

result = x * 2

print(result)
```

### Output

```text
tensor([20., 40., 60.])
```

### Real-World Example

In an image classification model, thousands of pixel values must be processed repeatedly. PyTorch provides efficient tensor operations for this.

### Key Point

> PyTorch is popular in Deep Learning because it combines tensors, automatic gradients, neural networks, and GPU support.

---

# 3. Tensor

### Simple Concept

A **tensor is the main data structure used by PyTorch**.

Think of it as a container for numbers.

```text
1D → [10, 20, 30]

2D → [[10, 20],
      [30, 40]]
```

### Why is it Needed?

Neural networks work with numerical data.

PyTorch uses tensors to store and process that data.

### Python Example

```python
import torch

marks = torch.tensor([85, 90, 78])

print(marks)
```

### Output

```text
tensor([85, 90, 78])
```

### Real-World Example

Student marks can be stored as:

```text
[85, 90, 78]
```

and passed to a PyTorch model.

### Key Point

> Tensor = PyTorch's main numerical data structure.

---

# 4. Tensor vs NumPy Array

### Simple Concept

Both NumPy arrays and PyTorch tensors store numbers.

The main difference is their purpose.

| NumPy                        | PyTorch             |
| ---------------------------- | ------------------- |
| Numerical computing          | Deep Learning       |
| Mainly CPU                   | CPU + GPU           |
| No automatic gradient system | Automatic gradients |
| `numpy.ndarray`              | `torch.Tensor`      |

### Why is it Needed?

You may use NumPy during data preparation and PyTorch for model training.

### Python Example

```python
import numpy as np
import torch

numpy_array = np.array([10, 20, 30])

tensor = torch.tensor([10, 20, 30])

print(type(numpy_array))
print(type(tensor))
```

### Output

```text
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
```

### Real-World Example

A dataset may be processed with NumPy first and then converted into PyTorch tensors before training.

### Key Point

> NumPy is mainly for numerical computing; PyTorch tensors are designed for Deep Learning workflows.

---

# 5. Creating Tensors

### Simple Concept

There are different ways to create tensors.

### Why is it Needed?

Before working with PyTorch, our data must exist as tensors.

### Python Example

```python
import torch

a = torch.tensor([10, 20, 30])

b = torch.zeros(3)

c = torch.ones(3)

d = torch.rand(3)

print(a)
print(b)
print(c)
print(d)
```

### Output

Example:

```text
tensor([10, 20, 30])
tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([0.XXXX, 0.XXXX, 0.XXXX])
```

Random values will be different each time.

### Real-World Example

A neural network contains weights.

These weights need initial values before training begins.

### Key Point

Common tensor creation functions:

```text
torch.tensor()
torch.zeros()
torch.ones()
torch.rand()
```

---

# 6. Tensor Shape

### Simple Concept

**Shape tells us the size of a tensor in each dimension.**

### Python Example

```python
import torch

customer_data = torch.tensor([
    [25, 2000, 12],
    [35, 3500, 24],
    [45, 5000, 36]
])

print(customer_data.shape)
```

### Output

```text
torch.Size([3, 3])
```

This means:

```text
3 rows
3 columns
```

### Why is it Needed?

Neural network layers expect data in specific shapes.

Knowing the shape helps us understand whether our data has the correct structure.

### Real-World Example

Suppose we have:

```text
1000 customers
5 features per customer
```

The shape is:

```text
[1000, 5]
```

### Key Point

> Shape tells us the size of the tensor.

---

# 7. Tensor Dimensions

### Simple Concept

Dimension tells us **how many axes a tensor has**.

### Python Example

```python
import torch

x = torch.tensor([
    [10, 20],
    [30, 40]
])

print(x.ndim)
```

### Output

```text
2
```

### Why is it Needed?

We need to know whether our data is 1D, 2D, 3D, etc., because different neural network operations expect different structures.

### Real-World Example

An RGB image can be represented as:

```text
Height × Width × Channels
```

For example:

```text
224 × 224 × 3
```

This is a 3-dimensional tensor.

### Key Point

```text
ndim = number of dimensions
```

---

# 8. Tensor dtype

### Simple Concept

`dtype` tells us **what type of numbers are stored inside the tensor**.

### Python Example

```python
import torch

x = torch.tensor([10.0, 20.0, 30.0])

print(x.dtype)
```

### Output

```text
torch.float32
```

We can also specify the dtype:

```python
x = torch.tensor(
    [10, 20, 30],
    dtype=torch.float32
)

print(x.dtype)
```

### Why is it Needed?

Deep Learning calculations commonly use floating-point numbers.

The dtype also affects memory usage and computation.

### Real-World Example

Customer data such as:

```text
Age = 29
Income = 50000
MonthlyCharges = 1200.50
```

is commonly represented as floating-point values before being passed to a neural network.

### Key Point

> dtype tells PyTorch what kind of numbers the tensor contains.

---

# 9. Tensor Indexing

### Simple Concept

Indexing means selecting a specific element.

### Python Example

```python
import torch

sales = torch.tensor([100, 200, 300])

print(sales[0])
print(sales[2])
```

### Output

```text
tensor(100)
tensor(300)
```

Remember:

```text
Index starts from 0
```

### Why is it Needed?

We often need to access individual values.

### Real-World Example

If:

```text
sales = [100, 200, 300]
```

then:

```python
sales[0]
```

could represent January sales.

### Key Point

> Indexing selects specific elements from a tensor.

---

# 10. Tensor Slicing

### Simple Concept

Slicing selects a **range of values**.

### Python Example

```python
import torch

sales = torch.tensor([
    100, 120, 140, 160, 180
])

print(sales[1:4])
```

### Output

```text
tensor([120, 140, 160])
```

### Why is it Needed?

We use slicing when we need only part of our data.

### Real-World Example

Suppose we have 12 months of sales.

We can slice the tensor to get sales for a particular group of months.

### Key Point

> Indexing gets specific elements; slicing gets a range of elements.

---

# 11. Tensor Reshaping

### Simple Concept

Reshaping changes the **structure** of a tensor without changing its values.

Example:

```text
[1, 2, 3, 4, 5, 6]
```

can become:

```text
[[1, 2, 3],
 [4, 5, 6]]
```

### Why is it Needed?

Different neural network layers may require different input shapes.

### Python Example

```python
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])

y = x.reshape(2, 3)

print(y)
```

### Output

```text
tensor([[1, 2, 3],
        [4, 5, 6]])
```

### Real-World Example

An image containing 784 pixels may need to be represented as:

```text
28 × 28
```

So:

```text
784 → 28 × 28
```

### Key Point

> Reshaping changes the structure, not the number of values.

---

# 12. `reshape()`

### Simple Concept

`reshape()` changes the shape of a tensor.

### Python Example

```python
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])

y = x.reshape(3, 2)

print(y)
```

### Output

```text
tensor([[1, 2],
        [3, 4],
        [5, 6]])
```

### Why is it Needed?

It is useful when the next operation or neural network layer expects a particular shape.

### Real-World Example

Suppose data is stored as:

```text
600 values
```

but the model expects:

```text
100 × 6
```

We can reshape it accordingly.

### Key Point

The number of elements must remain the same.

```text
6 = 3 × 2
```

---

# 13. `view()`

### Simple Concept

`view()` can also change the shape of a tensor.

### Python Example

```python
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])

y = x.view(2, 3)

print(y)
```

### Output

```text
tensor([[1, 2, 3],
        [4, 5, 6]])
```

### Why is it Needed?

It can be useful for changing tensor shape when the tensor has a compatible memory layout.

### `reshape()` vs `view()`

For now, remember:

```text
reshape() → flexible
view()    → requires compatible memory layout
```

`reshape()` is generally easier for beginners.

### Real-World Example

Before passing tensor data into a particular neural network layer, we may need to change its shape.

### Key Point

> Both can change shape, but `view()` has memory-layout requirements.

---

# 14. `flatten()`

### Simple Concept

`flatten()` converts multiple dimensions into one dimension.

### Python Example

```python
import torch

image = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

flat_image = image.flatten()

print(flat_image)
```

### Output

```text
tensor([1, 2, 3, 4, 5, 6])
```

### Why is it Needed?

Some neural network layers expect a 1D feature vector.

### Real-World Example

An image:

```text
28 × 28
```

contains:

```text
784 pixels
```

Flattening converts:

```text
28 × 28
   ↓
784
```

### Key Point

> `flatten()` is commonly used to convert image-like data into a single feature vector.

---

# 15. Tensor Arithmetic

### Simple Concept

PyTorch tensors support normal mathematical operations.

### Python Example

```python
import torch

price = torch.tensor([100, 200, 300])
quantity = torch.tensor([2, 3, 1])

revenue = price * quantity

print(revenue)
```

### Output

```text
tensor([200, 600, 300])
```

### Why is it Needed?

Neural networks perform many mathematical operations on tensors.

### Real-World Example

If:

```text
Price    = [100, 200, 300]
Quantity = [2,   3,   1]
```

then:

```text
Revenue = [200, 600, 300]
```

### Important

`*` means **element-wise multiplication**.

It does not mean matrix multiplication.

### Key Point

Common operations:

```python
x + y
x - y
x * y
x / y
```

---

# 16. Matrix Multiplication

### Simple Concept

Matrix multiplication combines rows from one matrix with columns from another.

### Python Example

```python
import torch

A = torch.tensor([
    [1, 2],
    [3, 4]
])

B = torch.tensor([
    [5, 6],
    [7, 8]
])

C = A @ B

print(C)
```

### Output

```text
tensor([[19, 22],
        [43, 50]])
```

### Why is it Needed?

Matrix multiplication is one of the most important operations inside a neural network.

A simplified neural network calculation looks like:

```text
Input × Weights + Bias
```

### Real-World Example

Suppose a customer has:

```text
Age
Income
Tenure
```

The neural network combines these inputs with learned weights using mathematical operations such as matrix multiplication.

### Key Point

```python
A @ B
```

means matrix multiplication.

---

# 17. Broadcasting

### Simple Concept

Broadcasting allows PyTorch to perform operations between tensors of compatible shapes.

### Python Example

```python
import torch

prices = torch.tensor([100, 200, 300])

tax = 10

final_price = prices + tax

print(final_price)
```

### Output

```text
tensor([110, 210, 310])
```

PyTorch effectively performs:

```text
100 + 10
200 + 10
300 + 10
```

### Why is it Needed?

Broadcasting lets us perform operations without writing loops.

### Real-World Example

Suppose every product has a ₹50 delivery charge:

```python
prices = torch.tensor([500, 800, 1200])

final_price = prices + 50
```

### Output

```text
tensor([550, 850, 1250])
```

### Key Point

> Broadcasting allows compatible shapes to work together automatically.

---

# 18. CPU vs GPU

### Simple Concept

CPU and GPU are processors used to perform calculations.

### CPU

Good for:

* Normal Python programs
* Small datasets
* Small models

### GPU

Good for:

* Large tensor calculations
* Large neural networks
* Large datasets
* Deep Learning training

### Why is it Needed?

Deep Learning can involve millions or billions of calculations.

A GPU can perform many suitable calculations in parallel.

### Python Example

```python
import torch

print("CUDA available:", torch.cuda.is_available())
```

### Output

Possible output:

```text
CUDA available: False
```

or:

```text
CUDA available: True
```

### Real-World Example

For a small beginner neural network:

```text
CPU → usually enough
```

For large image models:

```text
GPU → commonly used
```

### Key Point

> GPU is useful for accelerating large Deep Learning computations, but it is not required for every model.

---

# 19. Device Management

### Simple Concept

Device management means deciding where tensors and models will run:

```text
CPU
or
GPU
```

### Python Example

```python
import torch

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)
```

### Output

Possible output:

```text
cpu
```

or:

```text
cuda
```

Move a tensor to that device:

```python
x = torch.tensor([10, 20, 30])

x = x.to(device)

print(x.device)
```

### Why is it Needed?

The model and input data normally need to be on the same device.

For example:

```text
Model → GPU
Data  → GPU
```

### Real-World Example

If your neural network is running on GPU but your input tensor is still on CPU, PyTorch may produce a device mismatch error.

### Key Point

> `.to(device)` moves a tensor or model to the required device.

---

# 20. NumPy → PyTorch

### Simple Concept

A NumPy array can be converted into a PyTorch tensor.

### Python Example

```python
import numpy as np
import torch

array = np.array([10, 20, 30])

tensor = torch.from_numpy(array)

print(tensor)
print(type(tensor))
```

### Output

```text
tensor([10, 20, 30])
<class 'torch.Tensor'>
```

### Why is it Needed?

You may prepare data using NumPy and then need to use that data in PyTorch.

### Real-World Example

```text
NumPy preprocessing
       ↓
PyTorch Tensor
       ↓
Neural Network
```

### Key Point

```python
torch.from_numpy()
```

converts a NumPy array to a PyTorch tensor.

---

# 21. PyTorch → NumPy

### Simple Concept

A PyTorch tensor can be converted back to a NumPy array.

### Python Example

```python
import torch

tensor = torch.tensor([10, 20, 30])

array = tensor.numpy()

print(array)
print(type(array))
```

### Output

```text
[10 20 30]
<class 'numpy.ndarray'>
```

### Why is it Needed?

We may want to use NumPy for:

* Data analysis
* Calculations
* Visualization
* Some evaluation workflows

### Real-World Example

A PyTorch model produces predictions.

We can convert those predictions to NumPy for further analysis.

### Key Point

```python
tensor.numpy()
```

converts a CPU tensor to a NumPy array.

---

# 22. `torch.Tensor`

### Simple Concept

`torch.Tensor` is PyTorch's main tensor object.

### Python Example

```python
import torch

x = torch.tensor([10, 20, 30])

print(type(x))
```

### Output

```text
<class 'torch.Tensor'>
```

### Why is it Needed?

Almost everything in a PyTorch Deep Learning model works with tensors.

Examples:

```text
Input → Tensor
Weights → Tensor
Bias → Tensor
Output → Tensor
Gradient → Tensor
```

### Real-World Example

For a customer churn model:

```text
Customer data
     ↓
Tensor
     ↓
Neural Network
     ↓
Prediction tensor
```

### Key Point

> `torch.Tensor` is the fundamental numerical object used by PyTorch.

---

# 23. `requires_grad`

### Simple Concept

`requires_grad=True` tells PyTorch:

> Track the calculations involving this tensor because I may need its gradient.

### Python Example

```python
import torch

x = torch.tensor(5.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)
```

### Output

```text
tensor(10.)
```

### Easy Explanation

We created:

```text
x = 5
```

Then:

```text
y = x²
```

PyTorch tracked the calculation.

When we called:

```python
y.backward()
```

PyTorch calculated the gradient for `x`.

### Why is it Needed?

Neural networks learn by using gradients to update their weights.

Simplified:

```text
Prediction
    ↓
Loss
    ↓
Gradient
    ↓
Update weights
    ↓
Better model
```

### Real-World Example

During customer churn model training, the model's weights need gradients so PyTorch can determine how the weights should change to reduce prediction error.

### Key Point

> `requires_grad=True` enables gradient tracking for a tensor.

---

# 24. `torch.no_grad()`

### Simple Concept

`torch.no_grad()` tells PyTorch:

> Do not track gradients inside this block.

### Python Example

```python
import torch

x = torch.tensor(5.0, requires_grad=True)

with torch.no_grad():
    y = x ** 2

print(y)
print(y.requires_grad)
```

### Output

```text
tensor(25.)
False
```

### Why is it Needed?

During prediction, we usually don't need gradients.

We are not changing the model.

Therefore, tracking gradients would be unnecessary.

### Real-World Example

After training a customer churn model:

```text
New customer
     ↓
Trained model
     ↓
Prediction
```

We don't need to calculate gradients.

So:

```python
with torch.no_grad():
    prediction = model(new_data)
```

is commonly used.

### Key Point

> Use `torch.no_grad()` when you only need predictions and don't need gradient calculations.

---

# 25. Training vs Prediction

### Simple Concept

This connects `requires_grad` and `torch.no_grad()`.

### Training

```text
Input
 ↓
Model
 ↓
Prediction
 ↓
Loss
 ↓
Gradient
 ↓
Update Weights
```

Gradients are needed.

### Prediction

```text
Input
 ↓
Model
 ↓
Prediction
```

Gradients are normally not needed.

### Python Example

Training-style calculation:

```python
x = torch.tensor(5.0, requires_grad=True)

y = x ** 2

y.backward()

print(x.grad)
```

Prediction-style calculation:

```python
with torch.no_grad():
    prediction = x ** 2

print(prediction)
```

### Real-World Example

```text
Training:
Model learns from historical customer data.

Prediction:
Model predicts whether a new customer may leave.
```

### Key Point

```text
Training     → gradients needed
Prediction   → gradients usually not needed
```

---

# 26. Complete Mini Practice

### Simple Concept

Now combine the important tensor operations together.

### Python Example

```python
import torch

# Customer data:
# Age, Monthly Income, Tenure

customer_data = torch.tensor([
    [25.0, 2000.0, 12.0],
    [35.0, 3500.0, 24.0],
    [45.0, 5000.0, 36.0]
])

print("Customer Data:")
print(customer_data)

print("\nShape:")
print(customer_data.shape)

print("\nDimensions:")
print(customer_data.ndim)

print("\nData Type:")
print(customer_data.dtype)

print("\nFirst Customer:")
print(customer_data[0])

print("\nFirst Two Customers:")
print(customer_data[:2])
```

### Output

```text
Customer Data:
tensor([[  25., 2000.,   12.],
        [  35., 3500.,   24.],
        [  45., 5000.,   36.]])

Shape:
torch.Size([3, 3])

Dimensions:
2

Data Type:
torch.float32

First Customer:
tensor([  25., 2000.,   12.])

First Two Customers:
tensor([[  25., 2000.,   12.],
        [  35., 3500.,   24.]])
```

### What Does This Tell Us?

We have:

```text
3 customers
3 features
```

The features are:

```text
Age
Monthly Income
Tenure
```

Therefore:

```text
Shape = [3, 3]
```

means:

```text
3 customers × 3 features
```

### Real-World Example

This is similar to the data that would eventually be passed into a neural network for customer prediction.

---

# 27. How Everything Connects

The concepts in this notebook are not separate things.

They connect together:

```text
Real-World Data
      ↓
NumPy / Pandas
      ↓
PyTorch Tensor
      ↓
Check Shape / dtype / Dimensions
      ↓
Reshape / Flatten if required
      ↓
Move to CPU / GPU
      ↓
Tensor Operations
      ↓
Matrix Multiplication
      ↓
Neural Network
      ↓
Prediction
      ↓
Loss
      ↓
Gradient
      ↓
Weight Update
```

---

# 28. Final Revision

| Topic                 | What it means                 | Why we use it                    |
| --------------------- | ----------------------------- | -------------------------------- |
| PyTorch               | Deep Learning framework       | Build/train models               |
| Tensor                | PyTorch numerical container   | Store model data                 |
| Shape                 | Size of each dimension        | Check data structure             |
| Dimensions            | Number of axes                | Understand tensor structure      |
| dtype                 | Data type                     | Control numerical representation |
| Indexing              | Select element                | Access specific data             |
| Slicing               | Select range                  | Access part of data              |
| reshape()             | Change shape                  | Match required input shape       |
| view()                | Change shape                  | Reshape compatible tensors       |
| flatten()             | Make one dimension            | Prepare data for some layers     |
| Arithmetic            | Mathematical operations       | Perform calculations             |
| Matrix multiplication | Row × column calculation      | Core neural network operation    |
| Broadcasting          | Automatic shape compatibility | Avoid unnecessary loops          |
| CPU                   | General processor             | Small/normal workloads           |
| GPU                   | Parallel processor            | Large Deep Learning workloads    |
| Device                | CPU/GPU location              | Run model and data together      |
| NumPy → Tensor        | Convert data                  | Use NumPy data in PyTorch        |
| Tensor → NumPy        | Convert back                  | Analysis/visualization           |
| `torch.Tensor`        | Tensor object                 | Main PyTorch data structure      |
| `requires_grad`       | Track gradients               | Train neural networks            |
| `torch.no_grad()`     | Stop gradient tracking        | Efficient prediction             |

# 29. Most Important Mental Picture

Remember these three ideas first:

### 1. Tensor

```text
Tensor = Data
```

### 2. Matrix Operations

```text
Data × Weights + Bias
```

### 3. Gradient

```text
Prediction
    ↓
Error
    ↓
Gradient
    ↓
Adjust Weights
    ↓
Learn
```

That is the foundation for understanding what happens inside a PyTorch neural network.
