# Topic 1 – Why CNNs Are Used for Images

### Simple Concept

**CNN (Convolutional Neural Network)** is a type of neural network mainly designed to work with **images**.

An image contains many pixels. Instead of treating every pixel independently, CNN learns **patterns and features** from nearby pixels.

CNN can learn features such as:

- Edges
- Lines
- Shapes
- Textures
- Object parts
- Complete objects

### Why CNN?

A normal neural network can also process images, but it becomes inefficient when the image is large because there can be thousands or millions of pixels.

CNN solves this by looking at **small regions of the image at a time** and learning useful patterns.

For example:

**Image → Edges → Shapes → Object parts → Complete object**

### Real-World Example

Consider a **face recognition system**.

A CNN may learn:

**First layers:** edges and simple lines  
↓  
**Middle layers:** eyes, nose, mouth  
↓  
**Deeper layers:** complete face patterns  
↓  
**Output:** identifies the person or predicts whether a face is present

### Key Point

**CNNs are used for images because they can automatically learn spatial patterns and visual features from pixels.**

# Topic 2 – Image as a Tensor

### Simple Concept

In CNNs, an image is represented as a **tensor**.

A tensor is simply a data structure used to store numbers.

Since an image is made of pixels, each pixel is represented by a number.

For example, a small grayscale image:

```text
10   50   80
20   60   90
30   70   100
```

These numbers represent the **pixel intensity**.

- `0` → black
- `255` → white
- Values between them → shades of gray

So the image can be stored as a **2D tensor**:

```text
Height × Width
3 × 3
```

For a color image, we also have **channels**:

```text
Channels × Height × Width
3 × 224 × 224
```

where `3` represents:

- Red
- Green
- Blue


### Real-World Example

Suppose a camera captures a **224 × 224 RGB image**.

The CNN receives the image as numbers:

```text
3 × 224 × 224
```

The three channels contain the pixel values for:

```text
Red channel
Green channel
Blue channel
```

The CNN processes these numbers to identify visual patterns such as edges, shapes, and objects.

### Key Point

**Image → Pixel values → Tensor → CNN**

A CNN does not directly understand a picture like humans do. It receives the image as **numerical tensor data**.

# Topic 3 – Channels

### Simple Concept

A **channel** represents one layer of information in an image.

For a normal **RGB color image**, there are **3 channels**:

- **Red (R)**
- **Green (G)**
- **Blue (B)**

Each channel contains pixel values describing how much of that color is present.

### Image Shape

For an RGB image:

```text
Channels × Height × Width
3 × 224 × 224
```

For a grayscale image:

```text
Channels × Height × Width
1 × 224 × 224
```

So:

```text
RGB image      → 3 channels
Grayscale      → 1 channel
```

### Why Channels Matter in CNN

CNN processes the channels together to learn useful patterns.

For example, an image of a **red car** contains information from:

```text
Red channel
Green channel
Blue channel
```

The CNN combines this information to recognize the car's colors, edges, shapes, and other visual features.
`

### Real-World Example

Consider a **phone camera photo**.

The photo is usually an RGB image. Every pixel has information from:

```text
Red + Green + Blue
```

CNN uses these three channels to learn visual features and can eventually identify objects such as:

```text
Car
Person
Dog
Building
```

### Key Point

**Channel = one layer of image information.**

```text
RGB image → 3 channels
Grayscale image → 1 channel
```

In [1]:

### Python Example

import torch

# RGB image: 3 channels, 4 height, 4 width
image = torch.randn(3, 4, 4)

print(image.shape)

torch.Size([3, 4, 4])


# Topic 4 – Kernel / Filter

### Simple Concept

A **kernel (filter)** is a small matrix of numbers that moves across an image to detect a specific pattern.

For example, a simple **3 × 3 kernel**:

```text
1   0  -1
1   0  -1
1   0  -1
```

The kernel looks at small parts of the image and performs calculations with the pixel values.

Different filters can learn to detect different patterns, such as:

- Edges
- Lines
- Textures
- Shapes

### How It Works

The filter moves across the image:

```text
Image
  ↓
Small region
  ↓
Apply filter
  ↓
Calculate value
  ↓
Move filter
  ↓
Repeat
```

The collection of calculated values forms a **feature map**.

### Important Point

In a real CNN, we normally **do not manually choose the filter values**.

The neural network **learns the filter values during training**.

For example:

```text
Before training → filter values are initialized
During training → values are updated
After training → filters detect useful image patterns
```

### Real-World Example

Suppose a CNN is trained to recognize **cars**.

Some learned filters may detect:

```text
Edges → Wheels → Windows → Car body → Complete car
```

The CNN learns these filters automatically from training images.

### Key Point

**Kernel / Filter = small matrix that scans an image to detect patterns.**

```text
Image + Filter → Convolution → Feature Map
```

# Topic 5 – Convolution

### Simple Concept

**Convolution** is the process of applying a **kernel/filter** to an image to detect patterns.

The kernel moves across the image and performs a calculation at each position.

The basic process is:

```text
Image
  ↓
Place kernel on a small region
  ↓
Multiply image values × kernel values
  ↓
Add the results
  ↓
Move kernel
  ↓
Repeat
```

The resulting values form a **feature map**.

### Simple Example

Image:

```text
1  2  3
4  5  6
7  8  9
```

Kernel:

```text
1  0
0  1
```

For the first position:

```text
(1×1) + (2×0)
+ (4×0) + (5×1)

= 1 + 0 + 0 + 5

= 6
```

So the first value in the feature map is:

```text
6
```

The kernel then moves to the next position and performs the same calculation.


### Real-World Example

Imagine a CNN looking at a **cat image**.

A filter may move across the image and detect strong changes in pixel values.

These changes can represent:

```text
Edges → Shapes → Eyes / Ears → Cat
```

The convolution operation is what allows the CNN to extract these visual patterns.

### Key Point

**Convolution = sliding a filter over an image and calculating values to detect patterns.**

```text
Image + Kernel
      ↓
 Convolution
      ↓
 Feature Map
```

In [2]:

### Python Example

import torch
import torch.nn as nn

image = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.],
    [7., 8., 9.]
]).reshape(1, 1, 3, 3)

kernel = torch.tensor([
    [1., 0.],
    [0., 1.]
]).reshape(1, 1, 2, 2)

conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    bias=False
)

conv.weight.data = kernel

output = conv(image)

print(output)
print(output.shape)


tensor([[[[ 6.,  8.],
          [12., 14.]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 2, 2])


### Output Explanation

```text
torch.Size([1, 1, 3, 3])
```

This means:

```text
1 → Batch size
1 → Number of output channels / filters
3 → Output height
3 → Output width
```

We started with an image of:

```text
1 × 1 × 5 × 5
```

The `5 × 5` image was passed through a `3 × 3` convolution filter.

Because we did not use padding and the default stride is `1`, the spatial size becomes:

```text
5 × 5 → 3 × 3
```

So the convolution produces a **3 × 3 feature map**.

The important thing to understand is:

**Input Image → Convolution Filter → Smaller Feature Map**

The actual numbers in the feature map represent the strength of the pattern detected by the filter at different locations.

# Topic 7 – Stride

### Simple Concept

**Stride** tells the CNN **how many pixels the kernel moves at each step** across the image.

For example:

```text
Stride = 1
```

The kernel moves **1 pixel at a time**.

```text
Stride = 2
```

The kernel moves **2 pixels at a time**.

### Simple Example

Suppose we have a `5 × 5` image and a `3 × 3` kernel.

With:

```text
Kernel = 3 × 3
Stride = 1
```

The kernel moves one pixel at a time, producing a larger feature map.

With:

```text
Kernel = 3 × 3
Stride = 2
```

The kernel jumps two pixels at a time, producing a **smaller feature map**.

So:

**Larger stride → smaller output dimensions**


### Real-World Example

Imagine scanning a large image to find objects.

With **stride = 1**, the CNN checks almost every nearby position.

With **stride = 2**, it skips more positions and processes the image faster, but with less detailed spatial scanning.

### Key Point

**Stride controls how far the kernel moves.**

```text
Stride 1 → detailed scanning → larger output
Stride 2 → jumps further → smaller output
```

In [3]:

### Python Example

import torch
import torch.nn as nn

image = torch.randn(1, 1, 5, 5)

conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    stride=2
)

output = conv(image)

print(output.shape)


torch.Size([1, 1, 2, 2])



### Output Explanation

The input image is:

```text
1 × 1 × 5 × 5
```

Here:

```text
1 → Batch size
1 → Input channel
5 → Height
5 → Width
```

The convolution uses:

```text
Kernel = 3 × 3
Stride = 2
```

Because the kernel moves **2 pixels at a time**, the output becomes:

```text
5 × 5 → 2 × 2
```

The output shape is:

```text
1 × 1 × 2 × 2
```

The final `2 × 2` is the **feature map size**.

# Topic 8 – Padding

### Simple Concept

**Padding** means adding extra pixels around the border of an image before applying convolution.

Usually, we add **zeros** around the image.

Example:

Original image:

```text
1  2  3
4  5  6
7  8  9
```

After padding:

```text
0  0  0  0  0
0  1  2  3  0
0  4  5  6  0
0  7  8  9  0
0  0  0  0  0
```

### Why Padding Is Used

Without padding, the image becomes smaller after convolution.

Padding can:

- Preserve image dimensions
- Allow the filter to process border pixels
- Prevent information near the edges from being lost too quickly

### Common Padding

A common choice is:

```text
padding = 1
```

when using a `3 × 3` kernel with stride `1`.

For example:

```text
5 × 5 image
    ↓
3 × 3 kernel + padding = 1
    ↓
5 × 5 output
```

### Real-World Example

Suppose an important object is close to the **edge of an image**.

Without padding, convolution has fewer opportunities to process that border area.

With padding, extra space is added around the image, allowing the filter to process edge information better.

### Key Point

**Padding = adding extra pixels around the image to control the output size and preserve border information.**

```text
Without padding:
5 × 5 → 3 × 3

With padding = 1:
5 × 5 → 5 × 5
```

In [4]:

### Python Example
import torch
import torch.nn as nn

image = torch.randn(1, 1, 5, 5)

conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    stride=1,
    padding=1
)

output = conv(image)

print(output.shape)


torch.Size([1, 1, 5, 5])


```

### Output

```text
torch.Size([1, 1, 5, 5])
```

### Output Explanation

The input image is:

```text
1 × 1 × 5 × 5
```

The convolution uses:

```text
Kernel = 3 × 3
Stride = 1
Padding = 1
```

Because padding adds a border around the image, the spatial dimensions are maintained:

```text
5 × 5 → 5 × 5
```

So the output is:

```text
1 × 1 × 5 × 5
```

Here:

```text
1 → Batch size
1 → Output channel
5 → Output height
5 → Output width
```


# Topic 9 – Pooling

### Simple Concept

**Pooling** is a technique used in CNNs to **reduce the size of feature maps**.

It takes a small region of the feature map and summarizes the values into a single value.

For example:

```text id="5u2w1a"
2 × 2 region

1   5
3   4
```

Pooling converts this small region into **one value**.

The two common types are:

- **Max Pooling** → takes the largest value
- **Average Pooling** → takes the average value

### Why Pooling Is Used

Pooling helps to:

- Reduce the spatial size of feature maps
- Reduce computation
- Keep important information
- Make the network less sensitive to small changes in object position

Example:

```text id="lqf2mc"
Large Feature Map
       ↓
    Pooling
       ↓
Smaller Feature Map
```

### Output Explanation

The input feature map is:

```text id="a6otv5"
4 × 4
```

The `2 × 2` pooling window moves with:

```text id="4o7s4p"
Kernel size = 2
Stride = 2
```

It divides the feature map into four regions:

```text id="q2t1qv"
1   2 | 3   4
5   6 | 7   8
------+------
9  10 | 11  12
13 14 | 15  16
```

For each region, Max Pooling selects the largest value:

```text id="3f0v4c"
1,2,5,6       → 6
3,4,7,8       → 8
9,10,13,14    → 14
11,12,15,16   → 16
```

Therefore:

```text id="w9w6qv"
4 × 4 → 2 × 2
```

The output shape:

```text id="kq8l1j"
1 × 1 × 2 × 2
```

means:

```text
1 → Batch size
1 → Channel
2 → Height
2 → Width
```

### Real-World Example

Imagine a CNN detecting the **edge of a car**.

The exact location of the edge may change slightly between images.

Pooling keeps the important detected information while reducing the amount of data the CNN needs to process.

### Key Point

**Pooling reduces the size of feature maps while keeping important information.**

```text id="f7g5bn"
Feature Map
     ↓
   Pooling
     ↓
Smaller Feature Map
```

In [5]:

### Python Example

import torch
import torch.nn as nn

feature_map = torch.tensor([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.],
    [9., 10., 11., 12.],
    [13., 14., 15., 16.]
]).reshape(1, 1, 4, 4)

pool = nn.MaxPool2d(kernel_size=2, stride=2)

output = pool(feature_map)

print(output)
print(output.shape)


tensor([[[[ 6.,  8.],
          [14., 16.]]]])
torch.Size([1, 1, 2, 2])


# Topic 11 – Average Pooling

### Simple Concept

**Average Pooling** takes the **average of all values** inside a small region of a feature map.

For example:

```text
2 × 2 region

2   4
6   8
```

Average:

```text
(2 + 4 + 6 + 8) / 4 = 5
```

So the `2 × 2` region becomes:

```text
5
```

### How It Works

Suppose we have:

```text
1   5   2   4
3   7   1   8
9   2   6   4
5   3   7   2
```

Using:

```text
Kernel = 2 × 2
Stride = 2
```

The regions are:

```text
1   5 | 2   4
3   7 | 1   8
------+------
9   2 | 6   4
5   3 | 7   2
```

Calculate the average of each region:

```text
(1 + 5 + 3 + 7) / 4 = 4

(2 + 4 + 1 + 8) / 4 = 3.75

(9 + 2 + 5 + 3) / 4 = 4.75

(6 + 4 + 7 + 2) / 4 = 4.75
```

Output:

```text
4       3.75
4.75    4.75

### Output Explanation

The input feature map is:

```text
4 × 4
```

The `2 × 2` pooling window moves with a stride of `2`.

Therefore:

```text
4 × 4 → 2 × 2
```

Each output value is the **average of four input values**.

The output shape:

```text
1 × 1 × 2 × 2
```

means:

```text
1 → Batch size
1 → Channel
2 → Height
2 → Width
```

### Max Pooling vs Average Pooling

```text
Max Pooling     → selects the largest value
Average Pooling → calculates the average value
```

### Real-World Example

Suppose a CNN is analyzing a region containing a texture.

**Max Pooling** focuses on the strongest detected feature.

**Average Pooling** keeps the overall average information from that region.

### Key Point

**Average Pooling = calculate the average value of each region.**

```text
Feature Map
     ↓
Average Pooling
     ↓
Smaller Feature Map
```

In [7]:

### Python Example

import torch
import torch.nn as nn

feature_map = torch.tensor([
    [1., 5., 2., 4.],
    [3., 7., 1., 8.],
    [9., 2., 6., 4.],
    [5., 3., 7., 2.]
]).reshape(1, 1, 4, 4)

pool = nn.AvgPool2d(
    kernel_size=2,
    stride=2
)

output = pool(feature_map)

print(output)
print(output.shape)


tensor([[[[4.0000, 3.7500],
          [4.7500, 4.7500]]]])
torch.Size([1, 1, 2, 2])


# Topic 12 – Flattening

### Simple Concept

**Flattening** converts a multi-dimensional feature map into a **single 1D vector**.

CNN layers produce data like:

```text
Channels × Height × Width
```

Before sending this data to a fully connected layer, we flatten it.

```text
Feature Maps
     ↓
Flatten
     ↓
1D Vector
     ↓
Fully Connected Layer
```

### Simple Example

Suppose the CNN produces:

```text
2 × 2 feature map

1   2
3   4
```

After flattening:

```text
[1, 2, 3, 4]
```

The values are not changed. Only their **shape** changes.

### Output Explanation

The original shape is:

```text
1 × 1 × 2 × 2
```

which means:

```text
1 → Batch size
1 → Channel
2 → Height
2 → Width
```

After flattening:

```text
1 × 4
```

The `2 × 2` feature map contains:

```text
2 × 2 = 4 values
```

So those 4 values become one vector:

```text
[1, 2, 3, 4]
```

The **batch dimension is kept**, so the final shape is:

```text
[1, 4]
```

### Real-World Example

Suppose a CNN processes a **cat image**.

After several convolution and pooling layers, the CNN has extracted important cat features.

Before classification, those features need to be passed to a fully connected layer.

Flattening converts them into a format the fully connected layer can receive:

```text
Image
 ↓
CNN feature extraction
 ↓
Feature Maps
 ↓
Flatten
 ↓
Feature Vector
 ↓
Classification
```

### Key Point

**Flattening = converting feature maps into a 1D feature vector before the fully connected layer.**

In [8]:

### Python Example

import torch

feature_map = torch.tensor([
    [1., 2.],
    [3., 4.]
]).reshape(1, 1, 2, 2)

flatten = torch.flatten(feature_map, start_dim=1)

print(flatten)
print(flatten.shape)


tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])


# Topic 13 – Fully Connected Layer

### Simple Concept

A **Fully Connected (FC) layer**, also called a **Linear layer**, connects the input features to neurons in the next layer.

In a CNN, the fully connected layer is usually used **after flattening** to make the final prediction.

```text id="h1w3l4"
Feature Maps
     ↓
Flatten
     ↓
Fully Connected Layer
     ↓
Output
```

### What Does It Do?

The CNN's convolution and pooling layers extract useful features from the image.

The fully connected layer uses those extracted features to make a prediction.

For example, if a CNN is classifying animals:

```text id="1j4m5q"
Extracted features
       ↓
Fully Connected Layer
       ↓
Cat / Dog / Horse
```


### Output Explanation

The input is:

```text id="0ljq1g"
[1, 2, 3, 4]
```

There are **4 input features**, so:

```text id="f4zqxn"
in_features = 4
```

We created:

```text id="y2v0ma"
out_features = 2
```

So the layer has **2 output neurons**.

Therefore:

```text id="83s1ly"
4 features → 2 neurons
```

The output shape is:

```text id="6ohm7t"
[1, 2]
```

where:

```text id="y2t9u7"
1 → Number of samples
2 → Output values
```

If these two outputs represent two classes, the next step can use them for classification.

### Real-World Example

Suppose a CNN is trained to classify an image as:

```text id="2yywqi"
Cat
Dog
```

The convolution layers extract visual features such as edges, shapes, and object parts.

After flattening, the fully connected layer receives those features and produces values for the classes:

```text id="gk8n2x"
Features
   ↓
Fully Connected Layer
   ↓
Cat score | Dog score
```

The model can then use these outputs to determine the predicted class.

### Key Point

**Fully Connected Layer = uses the extracted features to produce outputs for the final prediction.**

```text id="u8f0p1"
Convolution
    ↓
Pooling
    ↓
Flatten
    ↓
Fully Connected
    ↓
Output
```

In [9]:
### Python Example

import torch
import torch.nn as nn

features = torch.tensor([
    [1., 2., 3., 4.]
])

fc = nn.Linear(
    in_features=4,
    out_features=2
)

output = fc(features)

print(output)
print(output.shape)


tensor([[ 0.6399, -2.1400]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])


# Topic 14 – CNN Architecture

### Simple Concept

A typical CNN processes an image step by step.

The basic architecture is:

```text
Image
  ↓
Convolution
  ↓
Activation
  ↓
Pooling
  ↓
Convolution
  ↓
Pooling
  ↓
Flatten
  ↓
Fully Connected
  ↓
Output
```

Each stage has a different purpose.

### 1. Image

The input image is represented as a tensor.

Example:

```text
3 × 224 × 224
```

This means:

```text
3 → RGB channels
224 → Height
224 → Width
```

### 2. Convolution

Filters scan the image and detect patterns such as:

```text
Edges → Lines → Shapes
```

### 3. Activation

An activation function such as **ReLU** is applied after convolution.

It helps the network learn complex patterns.

```text
Convolution → ReLU
```

### 4. Pooling

Pooling reduces the feature-map size while keeping important information.

```text
Large Feature Map
       ↓
    Pooling
       ↓
Small Feature Map
```

### 5. Second Convolution

Another convolution layer can learn more complex features.

For example:

```text
First layer  → Edges
Second layer → Shapes / Parts
```

### 6. Second Pooling

The feature map is reduced again.

This makes the data smaller before classification.

### 7. Flatten

The multi-dimensional feature maps are converted into a 1D vector.

```text
Feature Maps
     ↓
Flatten
     ↓
Feature Vector
```

### 8. Fully Connected Layer

The extracted features are used to make the final prediction.

### 9. Output

The final layer produces the prediction.

For example:

```text
Cat → 0.85
Dog → 0.15
```

The model would predict **Cat** because it has the higher output value.

### Real-World Example

Consider a CNN that identifies whether an image contains a **car or motorcycle**.

```text
Car/Motorcycle Image
        ↓
Convolution → Detect edges
        ↓
ReLU → Keep useful activations
        ↓
Pooling → Reduce size
        ↓
Convolution → Detect shapes and parts
        ↓
Pooling → Reduce size
        ↓
Flatten → Convert features to vector
        ↓
Fully Connected → Combine features
        ↓
Output → Car / Motorcycle
```

The important idea is that **early layers learn simple features and deeper layers combine them into more meaningful features**.

### Key Point

The CNN architecture can be remembered as:

```text
Image
 ↓
Convolution
 ↓
Activation
 ↓
Pooling
 ↓
Convolution
 ↓
Pooling
 ↓
Flatten
 ↓
Fully Connected
 ↓
Output
```

**Convolution extracts features → Pooling reduces size → Flatten prepares features → Fully Connected makes the prediction.**

# Topic 15 – Small Matrix Convolution Example

### Simple Concept

Let's manually perform convolution on a small matrix so you can clearly understand how a **kernel moves over an image**.

### Input Image

Consider this `4 × 4` image:

```text
1   2   3   4
5   6   7   8
9  10  11  12
13  14  15  16
```

### Kernel

Use a `2 × 2` kernel:

```text
1   0
0   1
```

We use:

```text
Kernel size = 2 × 2
Stride = 1
Padding = 0
```

### Step 1 – First Position

Take the first `2 × 2` region:

```text
1   2
5   6
```

Multiply with the kernel:

```text
(1 × 1) + (2 × 0)
+ (5 × 0) + (6 × 1)

= 1 + 0 + 0 + 6

= 7
```

First output value = **7**

### Step 2 – Move Right

Move the kernel **1 pixel to the right**:

```text
2   3
6   7
```

Calculation:

```text
(2 × 1) + (3 × 0)
+ (6 × 0) + (7 × 1)

= 9
```

Second output value = **9**

### Step 3 – Continue

The kernel continues moving across the image:

```text
1   2   3   4
5   6   7   8
9  10  11  12
13 14  15  16
```

The complete output becomes:

```text
7   9   11
15  17  19
23  25  27
```

Therefore:

```text
4 × 4 image
      ↓
2 × 2 kernel
      ↓
Stride = 1
      ↓
3 × 3 feature map
```

### Python Example

```python
import torch
import torch.nn as nn

image = torch.tensor([
    [1., 2., 3., 4.],
    [5., 6., 7., 8.],
    [9., 10., 11., 12.],
    [13., 14., 15., 16.]
]).reshape(1, 1, 4, 4)

kernel = torch.tensor([
    [1., 0.],
    [0., 1.]
]).reshape(1, 1, 2, 2)

conv = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=2,
    stride=1,
    padding=0,
    bias=False
)

conv.weight.data = kernel

output = conv(image)

print(output)
print(output.shape)
```

### Output

```text
tensor([[[[ 7.,  9., 11.],
          [15., 17., 19.],
          [23., 25., 27.]]]])

torch.Size([1, 1, 3, 3])
```

### Output Explanation

The input image has:

```text
4 × 4
```

The kernel has:

```text
2 × 2
```

With:

```text
Stride = 1
Padding = 0
```

the kernel can produce **3 positions horizontally** and **3 positions vertically**.

Therefore:

```text
4 × 4 → 3 × 3
```

The output shape:

```text
1 × 1 × 3 × 3
```

means:

```text
1 → Batch size
1 → Output channel
3 → Height
3 → Width
```

The `3 × 3` matrix is the **feature map**.

### Real-World Example

In a real image, the numbers represent pixel values.

A CNN filter might learn values that respond strongly to a particular pattern, such as an **edge**.

As the filter moves across the image, locations containing that pattern produce stronger values in the feature map.

### Key Point

The complete process is:

```text
Image
  ↓
Small region selected
  ↓
Multiply with kernel
  ↓
Add values
  ↓
Store result
  ↓
Move kernel
  ↓
Repeat
  ↓
Feature Map
```

This is the basic idea of **convolution in CNNs**.

# Topic 16 – Image Dimension Changes After Convolution and Pooling

### Simple Concept

During a CNN, the **height and width of the image/feature map can change** after convolution and pooling.

The important parameters are:

- **Kernel size**
- **Stride**
- **Padding**

### 1. Convolution Without Padding

Suppose:

```text id="r0y5ak"
Input = 5 × 5
Kernel = 3 × 3
Stride = 1
Padding = 0
```

Output:

```text id="z6my5q"
5 × 5 → 3 × 3
```

So the feature map becomes smaller.

### 2. Convolution With Padding

Suppose:

```text id="2s8x6v"
Input = 5 × 5
Kernel = 3 × 3
Stride = 1
Padding = 1
```

Output:

```text id="9q2a9h"
5 × 5 → 5 × 5
```

Padding helps preserve the spatial dimensions.

### 3. Convolution With Larger Stride

Suppose:

```text id="6mx1pz"
Input = 5 × 5
Kernel = 3 × 3
Stride = 2
Padding = 0
```

Output:

```text id="y8fq6m"
5 × 5 → 2 × 2
```

A larger stride causes the kernel to move farther each time, producing a smaller output.

### 4. Pooling

Suppose:

```text id="k5v4ye"
Input = 4 × 4
Pooling kernel = 2 × 2
Stride = 2
```

Output:

```text id="lqjz2a"
4 × 4 → 2 × 2
```

Pooling commonly reduces the height and width.

### Python Example

```python id="m4q0z8"
import torch
import torch.nn as nn

image = torch.randn(1, 1, 8, 8)

conv = nn.Conv2d(
    in_channels=1,
    out_channels=4,
    kernel_size=3,
    stride=1,
    padding=1
)

pool = nn.MaxPool2d(
    kernel_size=2,
    stride=2
)

conv_output = conv(image)
pool_output = pool(conv_output)

print("Input:", image.shape)
print("After Convolution:", conv_output.shape)
print("After Pooling:", pool_output.shape)
```

### Output

```text id="6r7w2t"
Input: torch.Size([1, 1, 8, 8])
After Convolution: torch.Size([1, 4, 8, 8])
After Pooling: torch.Size([1, 4, 4, 4])
```

### Output Explanation

#### Input

```text id="6q1v3b"
1 × 1 × 8 × 8
```

```text id="w7m3uo"
1 → Batch size
1 → Input channel
8 → Height
8 → Width
```

#### After Convolution

```text id="0h4x3u"
1 × 4 × 8 × 8
```

Why?

We used:

```text id="i4tq7n"
Kernel = 3 × 3
Stride = 1
Padding = 1
```

Padding preserves the `8 × 8` spatial size.

The number of channels changes from `1` to `4` because we created:

```text id="6nq0xk"
out_channels = 4
```

So there are **4 filters**, producing **4 feature maps**.

#### After Pooling

```text id="n1d5ef"
1 × 4 × 4 × 4
```

The `2 × 2` pooling with stride `2` reduces:

```text id="2g9qkg"
8 × 8 → 4 × 4
```

The number of channels remains `4`.

### Dimension Flow

A simple CNN might look like:

```text id="smw2iy"
Input
1 × 1 × 8 × 8
        ↓
Convolution
1 × 4 × 8 × 8
        ↓
Pooling
1 × 4 × 4 × 4
        ↓
Convolution
1 × 8 × 4 × 4
        ↓
Pooling
1 × 8 × 2 × 2
        ↓
Flatten
1 × 32
```

Notice:

- **Convolution can change the number of channels**
- **Pooling reduces height and width**
- **Flatten converts the remaining values into a vector**

### Real-World Example

For a large image, CNNs gradually reduce the spatial size while increasing the number of learned feature maps.

For example:

```text id="2p2gr8"
Image
224 × 224
   ↓
Feature Maps
112 × 112
   ↓
Feature Maps
56 × 56
   ↓
Feature Maps
28 × 28
   ↓
Flatten
   ↓
Classification
```

This allows the network to move from detailed pixel information toward higher-level visual features.

### Key Point

Remember these three ideas:

```text id="7am7o3"
Convolution → extracts features
Pooling     → reduces height and width
Channels    → represent different feature maps
```

And the most important dimension rule:

```text id="uv8g8g"
Pooling usually makes the image smaller.

Padding can preserve size.

Stride controls how much the kernel moves.
```
::